galaxy_info:
  author: Jules
  description: ASIMP Ubuntu OS updates and package checks
  company: ASIMP

  license: MIT

  min_ansible_version: "2.10"

  galaxy_tags:
    - system
    - security
    - updates

dependencies: []
