galaxy_info:
  author: Jules
  description: ASIMP Reporting and Compliance Audit
  company: ASIMP

  license: MIT

  min_ansible_version: "2.10"

  galaxy_tags:
    - auditing
    - security
    - openscap
    - lynis

dependencies: []
