---
- name: Check if debsums binary is available
  ansible.builtin.command: which debsums
  register: r_debsums_binary_check
  changed_when: false
  failed_when: false
  tags: debsums

- name: Run debsums check
  ansible.builtin.command: debsums -c
  when:
    - r_debsums_binary_check.rc == 0
    - (ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu')
    - debsums_ubuntu_check is defined
    - debsums_ubuntu_check
  changed_when: false
  tags: debsums
  ignore_errors: true
  async: 361
  poll: 0
  register: debsums_sleeper

- name: Run debsums check - check on async task
  ansible.builtin.async_status:
    jid: "{{ debsums_sleeper.ansible_job_id }}"
  register: debsums_job_result
  until: debsums_job_result.finished
  retries: 360
  when:
    - r_debsums_binary_check.rc == 0
    - (ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu')
    - debsums_ubuntu_check is defined
    - debsums_ubuntu_check
