title: "ASIMP Documentation"
description: "ASIMP (Ansible System Integrity Management Platform) is an automated security baseline, hardening, and compliance verification platform."
show_downloads: false
google_analytics:

# Navigation settings
navbar:
  - title: "Home"
    url: "/"
  - title: "Architecture & Design"
    url: "/architecture.html"
  - title: "OpenSCAP & Playbooks"
    url: "/openscap.html"
  - title: "Lynis & Playbooks"
    url: "/lynis.html"
  - title: "Configuration & Variables"
    url: "/configuration.html"
  - title: "Troubleshooting"
    url: "/troubleshooting.html"
  - title: "Legal Notice"
    url: "/legal-notice.html"

# Central default settings
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
